project_id = "jqrlegdulnnrpiixiecf"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.aura]
verify_jwt = false

[functions.activate-free-trial]
verify_jwt = false

[functions.renew-credits]
verify_jwt = false

[functions.get-stripe-mode]
verify_jwt = false

[functions.update-stripe-mode]
verify_jwt = false

[functions.cleanup-stale-credits]
verify_jwt = false

[functions.fetch-historical-prices]
verify_jwt = true

[functions.collective-insights]
verify_jwt = false

[functions.fetch-technical-indicators]
verify_jwt = false