project_id = "jqrlegdulnnrpiixiecf"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.portfolio-copilot]
verify_jwt = false

[functions.activate-free-trial]
verify_jwt = false

[functions.renew-credits]
verify_jwt = false